Feature: Company trusts and untrusts another company

  Background:
    Given there are following users:
       | person               | given_name |
       | kassi_testperson1    | Bosch      |
       | kassi_testperson2    | Siemens    |
    And I am logged in as "kassi_testperson1"
    And I am a "basic" user
    And "kassi_testperson2" is a "basic" user

  @javascript
  Scenario: Company trusts another company
    When I go to the profile page of "kassi_testperson2"
    And I follow "Trust"
    Then I should see "Configure your relationship with device pool Siemens"
    And I should see "Trust pool admin & pool users"
    And I should see ""
    And I should see "Always confirm"
    When I press "Save"
    Then I should see "Bosch" within ".profile-title"
    Then I should see "Siemens" within "#profile-followed-people-list"
    And "kassi_testperson2@example.com" should have 1 email

    # Other company gets notification
    When I log out
    And I log in as "kassi_testperson2"
    When I follow inbox link
    Then I should see "(This message is auto-generated by RENTOG)"

  @javascript
  Scenario: Company untrusts another company
    Given "kassi_testperson1" follows "kassi_testperson2"
    When I go to the profile page of "kassi_testperson2"
    And I follow "Untrust"
    And I will confirm all following confirmation dialogs in this page if I am running PhantomJS
    And I confirm alert popup
    Then I should see "Trust" within ".profile-action-buttons-desktop"
    And I should see "Successfully removed trusted status from other device pool"
    And I should not see "Trusted" within ".profile-action-buttons-desktop"
    When I go to my profile page
    Then I should see "No trusted device pool"
    And "kassi_testperson2@example.com" should have 1 email

    # Other company gets notification
    When I log out
    And I log in as "kassi_testperson2"
    And I follow inbox link
    Then I should see "(This message is auto-generated by RENTOG)"


