class PopulateManufacturerCustomFieldWithData < ActiveRecord::Migration
  def up
    hersteller_field_id = Maybe(CustomFieldName.where(:value => "Manufacturer").first).custom_field_id.to_i.or_else(nil)
    last_sort_prio = CustomFieldOption.where(custom_field_id: hersteller_field_id).order(:sort_priority).last.sort_priority
    manufacturers = ["AFL Telecommunications",
      "AFRISO-EURO-INDEX GmbH",
      "Agilent",
      "Ahlborn Mess- und Regelungstechnik GmbH",
      "Aim-Tti",
      "Airflow",
      "Airtec",
      "Altek",
      "Altinex",
      "Altium Designer",
      "Amec",
      "American Power Conversation",
      "Ameritec Corp.",
      "Amherst Systems Associates, Inc.",
      "AMOtronics UG",
      "Amplifier Research",
      "Andilog Technologies",
      "Ando Electric Co",
      "Anritsu",
      "Anton Paar GmbH",
      "Aoip",
      "AP Sensing",
      "Applied Relay Testing",
      "Argweld",
      "Ariadna Instruments",
      "Arrray",
      "Ascom",
      "Associated Research, Inc.",
      "Astrodesign inc",
      "Astromed",
      "Audio Precision",
      "AYA Instruments",
      "B2 High Voltage",
      "Bacharach",
      "Baker Instruments",
      "Ballantine",
      "Baur",
      "Belkin",
      "Beninng",
      "Bently Nevada",
      "Berkley Nucleonics Corporation",
      "BestSens AG",
      "Bicotest",
      "Binder GmbH",
      "Bird Electronics Corp.",
      "BK Prescion",
      "BMC Messsysteme GmbH",
      "Boger",
      "Bonn Elektronik",
      "Boonton Electronics Corp.",
      "Bosch",
      "Bowthorpe",
      "Brehmer GmbH & Co. KG",
      "Bristol Babcock",
      "Broady",
      "Bruel & Kjaer Instruments, Inc.",
      "BS-rep GmbH",
      "Budenberg",
      "Bürkert",
      "Burster",
      "BW Technologies",
      "Caemax Technologie GmbH",
      "California Instruments",
      "Calmet Ltd.",
      "Calnex",
      "Camlin Power",
      "Casella Measurement",
      "Catu",
      "CEL Instruments",
      "Centellax",
      "Chase Electrics",
      "Chauvin Arnoux",
      "Chessell",
      "Chroma Systems Solutions, Inc.",
      "Circutor",
      "Cirrus Research",
      "Clare Instruments",
      "Cleverscope",
      "CMV Hoven GmbH",
      "Comark Instruments",
      "Combinova",
      "Comdronic",
      "Communications Components Inc.",
      "Connecticut Technology Product",
      "CorDEX Instruments",
      "Corning",
      "Crescent Heart Software",
      "Cropico",
      "Crowcon Detection Instruments",
      "Crystalline Mirror Solutions GmbH",
      "Cutler-Hammer",
      "Cygnus Instruments",
      "Dart Systems",
      "Data Presicion",
      "Data Translation GmbH",
      "Datron",
      "Delphin Technology AG",
      "Delta",
      "Dewetron",
      "Dias Infrared GmbH",
      "Digimess",
      "Digitron",
      "DILO Armaturen und Anlagen GmbH",
      "Disynet GmbH",
      "D-Link Systems Inc.",
      "Doble Engineering",
      "Dr. Brockhaus Messtechnik",
      "Dranetz",
      "Driesen+Kern GmbH",
      "Druck",
      "DVP",
      "Dynamic Ratings",
      "E+E ELEKTRONIK Ges.m.b.H.",
      "EA Elektroautomatik",
      "Ectron",
      "Eiden",
      "EIP",
      "EIP Microwave",
      "Elabo",
      "Elcometer",
      "Elcomponent",
      "Elcon International AB ",
      "Electro Metrics",
      "Electrometrics",
      "Elektro - Automatik",
      "Elgar",
      "EM TEST",
      "EMC Partner AG ",
      "Emco",
      "Emerson ",
      "EMH Energie-Messtechnik GmbH",
      "EMSCAN",
      "Emsystech Engineering",
      "Endevco",
      "Enensys",
      "Entek IRD International",
      "Entel",
      "EPRO Gellspach",
      "ET System Electronic",
      "E-Technology Wrobel",
      "EuroSMC",
      "Everest VIT",
      "Exfo",
      "Extech Instruments",
      "Faro",
      "Finisar",
      "Fischer Customs Communications",
      "Fitel",
      "Flann Microwave Ltd",
      "Flexim",
      "Flir",
      "Fluke",
      "Focus Microwaves",
      "Fogtec",
      "FRANCELOG Electronique S.A.",
      "FUG Elektronik",
      "Fujikura",
      "Furness Controls",
      "Furukawa",
      "GANTNER Instruments",
      "Gas Measurement Instruments Ltd ",
      "General Electric",
      "Genex",
      "GenRad",
      "GHM Messtechnik GmbH",
      "Gigatronics",
      "GMC Instruments",
      "Gnubi",
      "Good Will Instrument Co Ltd",
      "Gossen Metrawatt",
      "Graphtec",
      "Guanglu",
      "GW Instek",
      "H.V. Sullivan",
      "Haefely Test Systems",
      "Hameg",
      "Hantek ",
      "haomai electrical ",
      "Hart Scientific",
      "Hatfield",
      "Heiden",
      "Heine",
      "Heinzinger",
      "Helzel",
      "HEME",
      "Hewlett Packard",
      "Hi-Force",
      "High Voltage",
      "Highvolt",
      "Hilti",
      "Hioki",
      "Hipotronics",
      "Hirst Magnetic Instruments",
      "Hitachi",
      "Holaday Industries",
      "Honeywell",
      "HT Instruments",
      "HTL - Hydra Press Systems",
      "Huber & Suhner",
      "Hughes",
      "HV Diagnostics",
      "HV Technologies",
      "HVPD",
      "Hydratron",
      "Hydrotechnik GmbH",
      "I.S.A. Istrumentazioni Sistemi Automatici",
      "Ibeko Power AB",
      "imc Meßsysteme GmbH ",
      "Ingeteam",
      "Instantel",
      "Instek",
      "InterEng GmbH",
      "Interface Components Limited",
      "Iso-Tech",
      "Ithaco",
      "IXIA Communications",
      "Javac",
      "JDS Uniphase",
      "JDSU",
      "JFW Industries",
      "JMA Wireless",
      "Jofra",
      "Kafer",
      "Kane",
      "Karl Storz",
      "Kathrein",
      "Katronic Technologies",
      "Keithley",
      "Keller Group",
      "Kennedy",
      "Kenwood",
      "Keopsys",
      "Kepco",
      "Keysight Technologies",
      "Keytek",
      "Kikusui",
      "Kilovolt",
      "Kimo Instruments",
      "Kingsine Electric Automation Co.",
      "KNESTEL Technologies",
      "KoCoS Messtechnik AG",
      "KROHNE Messtechnik GmbH",
      "Krohn-Hite",
      "Ladybug",
      "Lambda",
      "Land Ametek",
      "Leader",
      "LeCroy",
      "Lee Vaughan",
      "Leica",
      "LEM HEME",
      "Lindos",
      "LitePoint",
      "LMW Electronics Ltd",
      "LTX-Credance corp",
      "Lucas Weinschel",
      "Lucy Electric",
      "Lüthi",
      "Lyons",
      "Magnum",
      "Manta Test Systems",
      "Marconi",
      "Marconi Instruments",
      "Martindale Electric",
      "Master",
      "Maury Microwave",
      "Meatest",
      "Megger",
      "Metra Meß- und Frequenztechnik",
      "Metrel",
      "Metric",
      "Metrix",
      "Metrohm",
      "Mettler Toledo",
      "Michell Instruments GmbH",
      "Micronetics",
      "Microtest",
      "Midtronics, Inc.",
      "Millivac",
      "Milmega",
      "Mini Circuits",
      "Minolta",
      "Miopas GmbH",
      "Monitran",
      "Multimetrix",
      "Narda Microwave Corporation",
      "Narda Safety Test Solutions GmbH",
      "National Instruments",
      "NetOptics",
      "NetScout",
      "Nettest",
      "Neumann Elektrotechnik",
      "Newport Digital",
      "Nicolet Technologies",
      "Nixon Flowmeters",
      "Noise Com",
      "Norbar",
      "Norma",
      "Noyes",
      "OFS Fitel",
      "Olympus",
      "Omicron",
      "Ophir RF",
      "Optronics",
      "Oxford instruments",
      "Pacific Power",
      "Pacific Power Source Corporation",
      "Palmer Environmental",
      "Pasternack",
      "PCE Deutschland GmbH ",
      "PCE Instruments UK Ltd",
      "PCTEL",
      "Pea Soup",
      "Peak Beam Systems Inc",
      "PeakTech",
      "Peekel Instruments GmbH",
      "Pelican Products, Inc.",
      "Pendulum Instruments, Inc.",
      "Phase Matrix, Inc.",
      "Phenix Technologies",
      "Photonetics",
      "Pico Technology",
      "Plisch",
      "PM Microwave",
      "PMK Mess- und Kommunikationstechnik GmbH",
      "Polysonics",
      "Polytec GmbH",
      "Pomona Electronics",
      "Ponovo Power",
      "Power Diagonstix Systems",
      "Powerbox",
      "Powertek LLC",
      "Pragmatic",
      "Pramac",
      "Praxsym, Inc.",
      "Precision Filters, Inc.",
      "Priorspec",
      "Proceq",
      "Programma",
      "PROMAX Electronica S. L.",
      "pro-micron GmbH & Co. KG",
      "Protek",
      "Pruftechnik",
      "QuadTech",
      "QuantumData",
      "Quartzlock",
      "Quinstar",
      "Racal",
      "Racal Dana",
      "Radian Research",
      "Radiodetection",
      "Raytech USA",
      "RECKMANN GMBH ",
      "Reynolds Industries",
      "RF Industries",
      "RGB Lasersysteme GmbH",
      "RH Systems",
      "RIEGL Laser Measurement Systems GmbH",
      "Rigol",
      "RM Prüftechnik GmbH",
      "Robin",
      "Rohde & Schwarz",
      "Rolux",
      "Roschi Rohde & Schwarz AG",
      "Rosemount",
      "Rotary Regavolt",
      "Rotronic Messgeräte gmbh",
      "Sage Labs",
      "Sapphire Instruments",
      "SAXON Junkalor GmbH",
      "Schaffner EMC, Incorporated",
      "Schneider Electric",
      "Schwarzbeck",
      "Seaward",
      "SebaKMT",
      "Sefelec",
      "Sefram Instruments & Systems",
      "Sencore",
      "Sensor Instruments GmbH",
      "Sensorlink Corporation",
      "Shaw",
      "Shiba Soku",
      "ShinewayTech",
      "Si Pressure Instruments",
      "Siglent",
      "Sika",
      "SI-special instruments GmbH",
      "SlopeView",
      "Sofimation",
      "Solartron",
      "Solex",
      "Sommer GmbH",
      "SONEL S.A. ",
      "Sorensen",
      "Soundtec GmbH",
      "Sourcetronic GmbH",
      "Spectracom",
      "SPEKTRA",
      "Spinner",
      "Spirent Communications",
      "SPS Electronic",
      "STACK ELECTRONICS CO., LTD",
      "Stanford Research",
      "Starrett",
      "Stevo Electric",
      "Storage Battery Systems LLC",
      "Straton",
      "Suhner",
      "Sumitomo",
      "Sunrise Telecom",
      "Sunsight Instruments",
      "SureWave Technology Ltd",
      "Svantek",
      "Swema",
      "Symmetricom Inc.",
      "Synaccess Networks Inc.",
      "Synthesys Research",
      "Systron Donner",
      "T&R Test Equipment Ltd.",
      "Tabor",
      "Tamat",
      "TC Mess- und Regeltechnik GmbH",
      "Techimp  ",
      "Technifor",
      "Tektronix",
      "Telegan",
      "Telemeter Electronic GmbH",
      "Temperaturmeßtechnik Geraberg GmbH",
      "Tenney Engineering",
      "Tescom",
      "Testo",
      "Testoterm",
      "Thurlby Thandar Instruments",
      "Time Electronics",
      "Toa",
      "Toellner",
      "TOPAG Lasertechnik GmbH",
      "Toshiba",
      "Tracerco",
      "Transistor Devices Inc.",
      "Transmation",
      "Trend Communications",
      "Tresna",
      "Trotec",
      "TTC",
      "UE Systems",
      "UIT Networks",
      "Unigraf",
      "Unitronics Electric",
      "Vaisala",
      "Valhalla",
      "Validyne",
      "Vanguard Instruments",
      "Varian Associates",
      "Velleman",
      "VeriWave",
      "Viavi Solutions",
      "Vishay Measurement Group",
      "Vitrek",
      "Voetsch",
      "Voltech",
      "Wainwright",
      "Walther Electric GmbH",
      "Wavetek",
      "Wayne Kerr",
      "Weldwide Solutions",
      "Wens",
      "West Bond Inc.",
      "Westover Scientific",
      "Willtek Communications",
      "Wiltron",
      "WL Gore",
      "Wohler",
      "Wölfel Meßsysteme",
      "Woodward",
      "Xantrex Technology",
      "XL Microwave",
      "Yokogawa",
      "Zeiss",
      "ZENSOL AUTOMATION INC. ",
      "Zera",
      "ZES"]

    manufacturers.each do |manufacturer|
      last_sort_prio += 1
      new_custom_field_option = CustomFieldOption.new(custom_field_id: hersteller_field_id, sort_priority: last_sort_prio)
      new_custom_field_option_title = CustomFieldOptionTitle.create(:locale => "en", :value => manufacturer)
      new_custom_field_option.titles << new_custom_field_option_title
      new_custom_field_option.save
      new_custom_field_option_title.update_attribute(:custom_field_option_id, new_custom_field_option.id)
    end
  end
end
